#!/bin/bash

if (git diff --cached --name-only | grep --silent '\.go$'); then

    make lint
    if [ $? -ne 0 ]; then
        echo "golangci-lint failed. You can try 'make fix' to automatically fix some issues. Commit aborted."
        exit 1
    fi

    make test
    if [ $? -ne 0 ]; then
        echo "Tests failed. Commit aborted."
        exit 1
    fi
fi
