// Code generated by "stringer -type=CommandStatus"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[Timeout-1]
	_ = x[NoSelect-2]
	_ = x[FormatError-3]
	_ = x[CommandNotSupported-4]
	_ = x[AlreadyActive-5]
	_ = x[HardwareError-6]
	_ = x[Local-7]
	_ = x[TooManyOps-8]
	_ = x[NotAuthorized-9]
	_ = x[AutomationInhibit-10]
	_ = x[ProcessingLimited-11]
	_ = x[OutOfRange-12]
	_ = x[DownstreamLocal-13]
	_ = x[AlreadyComplete-14]
	_ = x[Blocked-15]
	_ = x[Canceled-16]
	_ = x[BlockedOtherMaster-17]
	_ = x[DownstreamFail-18]
	_ = x[NonParticipating-126]
}

const (
	_CommandStatus_name_0 = "SuccessTimeoutNoSelectFormatErrorCommandNotSupportedAlreadyActiveHardwareErrorLocalTooManyOpsNotAuthorizedAutomationInhibitProcessingLimitedOutOfRangeDownstreamLocalAlreadyCompleteBlockedCanceledBlockedOtherMasterDownstreamFail"
	_CommandStatus_name_1 = "NonParticipating"
)

var (
	_CommandStatus_index_0 = [...]uint8{0, 7, 14, 22, 33, 52, 65, 78, 83, 93, 106, 123, 140, 150, 165, 180, 187, 195, 213, 227}
)

func (i CommandStatus) String() string {
	switch {
	case i <= 18:
		return _CommandStatus_name_0[_CommandStatus_index_0[i]:_CommandStatus_index_0[i+1]]
	case i == 126:
		return _CommandStatus_name_1
	default:
		return "CommandStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
