// Code generated by "stringer -type=DataLinkSecondaryFC"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ack-0]
	_ = x[Nack-1]
	_ = x[LinkStatus-11]
	_ = x[NotSupported-15]
}

const (
	_DataLinkSecondaryFC_name_0 = "AckNack"
	_DataLinkSecondaryFC_name_1 = "LinkStatus"
	_DataLinkSecondaryFC_name_2 = "NotSupported"
)

var (
	_DataLinkSecondaryFC_index_0 = [...]uint8{0, 3, 7}
)

func (i DataLinkSecondaryFC) String() string {
	switch {
	case i <= 1:
		return _DataLinkSecondaryFC_name_0[_DataLinkSecondaryFC_index_0[i]:_DataLinkSecondaryFC_index_0[i+1]]
	case i == 11:
		return _DataLinkSecondaryFC_name_1
	case i == 15:
		return _DataLinkSecondaryFC_name_2
	default:
		return "DataLinkSecondaryFC(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
