// Code generated by "stringer -type=DataLinkPrimaryFunctionCode"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResetLinkStates-0]
	_ = x[TestLinkStates-2]
	_ = x[ConfirmedUserData-3]
	_ = x[UnconfirmedUserData-4]
	_ = x[RequestLinkStatus-9]
}

const (
	_DataLinkPrimaryFunctionCode_name_0 = "ResetLinkStates"
	_DataLinkPrimaryFunctionCode_name_1 = "TestLinkStatesConfirmedUserDataUnconfirmedUserData"
	_DataLinkPrimaryFunctionCode_name_2 = "RequestLinkStatus"
)

var (
	_DataLinkPrimaryFunctionCode_index_1 = [...]uint8{0, 14, 31, 50}
)

func (i DataLinkPrimaryFunctionCode) String() string {
	switch {
	case i == 0:
		return _DataLinkPrimaryFunctionCode_name_0
	case 2 <= i && i <= 4:
		i -= 2
		return _DataLinkPrimaryFunctionCode_name_1[_DataLinkPrimaryFunctionCode_index_1[i]:_DataLinkPrimaryFunctionCode_index_1[i+1]]
	case i == 9:
		return _DataLinkPrimaryFunctionCode_name_2
	default:
		return "DataLinkPrimaryFunctionCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
