// Code generated by "stringer -type=PointPrefixCode"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoPrefix-0]
	_ = x[Index1Octet-1]
	_ = x[Index2Octet-2]
	_ = x[Index4Octet-3]
	_ = x[Size1Octet-4]
	_ = x[Size2Octet-5]
	_ = x[Size4Octet-6]
	_ = x[Reserved-7]
}

const _PointPrefixCode_name = "NoPrefixIndex1OctetIndex2OctetIndex4OctetSize1OctetSize2OctetSize4OctetReserved"

var _PointPrefixCode_index = [...]uint8{0, 8, 19, 30, 41, 51, 61, 71, 79}

func (i PointPrefixCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PointPrefixCode_index)-1 {
		return "PointPrefixCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PointPrefixCode_name[_PointPrefixCode_index[idx]:_PointPrefixCode_index[idx+1]]
}
