// Code generated by "stringer -type=RangeSpecCode"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StartStop1-0]
	_ = x[StartStop2-1]
	_ = x[StartStop4-2]
	_ = x[VirtualStartStop1-3]
	_ = x[VirtualStartStop2-4]
	_ = x[VirtualStartStop4-5]
	_ = x[NoRangeField-6]
	_ = x[Count1-7]
	_ = x[Count2-8]
	_ = x[Count4-9]
	_ = x[ReservedA-10]
	_ = x[Count1Variable-11]
	_ = x[ReservedC-12]
	_ = x[ReservedD-13]
	_ = x[ReservedE-14]
	_ = x[ReservedF-15]
}

const _RangeSpecCode_name = "StartStop1StartStop2StartStop4VirtualStartStop1VirtualStartStop2VirtualStartStop4NoRangeFieldCount1Count2Count4ReservedACount1VariableReservedCReservedDReservedEReservedF"

var _RangeSpecCode_index = [...]uint8{0, 10, 20, 30, 47, 64, 81, 93, 99, 105, 111, 120, 134, 143, 152, 161, 170}

func (i RangeSpecCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RangeSpecCode_index)-1 {
		return "RangeSpecCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RangeSpecCode_name[_RangeSpecCode_index[idx]:_RangeSpecCode_index[idx+1]]
}
