// Code generated by "stringer -type=RequestFunctionCode"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Confirm-0]
	_ = x[Read-1]
	_ = x[Write-2]
	_ = x[Select-3]
	_ = x[Operate-4]
	_ = x[DirOperate-5]
	_ = x[DirOperateNoAck-6]
	_ = x[Freeze-7]
	_ = x[FreezeNoAck-8]
	_ = x[FreezeClear-9]
	_ = x[FreezeClearNoAck-10]
	_ = x[FreezeAtTime-11]
	_ = x[FreezeAtTimeNoAck-12]
	_ = x[ColdRestart-13]
	_ = x[WarmRestart-14]
	_ = x[InitializedData-15]
	_ = x[InitializeApplication-16]
	_ = x[StartApplication-17]
	_ = x[StopApplication-18]
	_ = x[SaveConfiguration-19]
	_ = x[EnableUnsolicited-20]
	_ = x[DisableUnsolicited-21]
	_ = x[AssignClass-22]
	_ = x[DelayMeasurement-23]
	_ = x[RecordCurrentTime-24]
	_ = x[OpenFile-25]
	_ = x[CloseFile-26]
	_ = x[DeleteFile-27]
	_ = x[GetFileInformation-28]
	_ = x[AuthenticateFile-29]
	_ = x[AbortFile-30]
	_ = x[ActivateConfig-31]
	_ = x[AuthenticationRequest-32]
	_ = x[AuthenticationRequestNoAck-33]
}

const _RequestFunctionCode_name = "ConfirmReadWriteSelectOperateDirOperateDirOperateNoAckFreezeFreezeNoAckFreezeClearFreezeClearNoAckFreezeAtTimeFreezeAtTimeNoAckColdRestartWarmRestartInitializedDataInitializeApplicationStartApplicationStopApplicationSaveConfigurationEnableUnsolicitedDisableUnsolicitedAssignClassDelayMeasurementRecordCurrentTimeOpenFileCloseFileDeleteFileGetFileInformationAuthenticateFileAbortFileActivateConfigAuthenticationRequestAuthenticationRequestNoAck"

var _RequestFunctionCode_index = [...]uint16{0, 7, 11, 16, 22, 29, 39, 54, 60, 71, 82, 98, 110, 127, 138, 149, 164, 185, 201, 216, 233, 250, 268, 279, 295, 312, 320, 329, 339, 357, 373, 382, 396, 417, 443}

func (i RequestFunctionCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RequestFunctionCode_index)-1 {
		return "RequestFunctionCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestFunctionCode_name[_RequestFunctionCode_index[idx]:_RequestFunctionCode_index[idx+1]]
}
