// Code generated by "stringer -type=ResponseFC"; DO NOT EDIT.

package dnp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Response-129]
	_ = x[UnsolicitedResponse-130]
	_ = x[AuthenticationResponse-131]
}

const _ResponseFC_name = "ResponseUnsolicitedResponseAuthenticationResponse"

var _ResponseFC_index = [...]uint8{0, 8, 27, 49}

func (i ResponseFC) String() string {
	idx := int(i) - 129
	if i < 129 || idx >= len(_ResponseFC_index)-1 {
		return "ResponseFC(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseFC_name[_ResponseFC_index[idx]:_ResponseFC_index[idx+1]]
}
